### ISSUE TITLE
Link to pyvcontrol

### ISSUE THREAD

**Issue by joppi588** [tsvsj/pyvcontrold-net#1]
https://github.com/joppi588/pyvcontrol

Ist ein Python Paket das direkt mit der Viessmann spricht, ohne vcontrold.
Ich würde mich freuen wenn du das Paket oben in deiner README erwähnen könntest.

Grüße

Jochen

**Comment by tsvsj** [comment]
Hi Jochen,

klar doch. Danke für den Hinweis.


Beste Grüße
